language: ruby
rvm:
- 2.1.2
test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres
addons:
  postgresql: '9.3'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
deploy:
  provider: heroku
  api_key:
    secure: Aph84vda3xmUez4kL9TdSh3wTs3qlNjjllfg6StIqBcGSnPJSLKuWbaSZwnpAplMO4TNOwMAojjkcpPAmkabyR+HHv34p5+JPkmHGIYDxZ1Fx3Oh0OfpgbyQ5mJZ3FeAzvdKJlOWRkIMC9W4jfN9R0xcvfnpwWrap/JvxlKFTHE=
  app: whispering-harbor-7929
  on:
